console.log("You are writing text to yo ur screen.")
console.log("Ths is called 'standard output'.")
console.log("This stuff in the () is a string.")
console.log("Start a string with a double-quote.")
console.log("Write what you want.")
console.log("Then end with a double-quote.")
